export const getSlug = (item) => (item ? item.slug : null)
export const getTitle = (item) => (item ? item.slug : null)
export const getOverview = (item) => (item ? item.slug : null)
export const getProfileBio = (item) => (item ? item.slug : null)
export const getAuthor = (item) => (item ? item.author : null)
export const getCoverImage = (item) => (item ? item.image : null)
export const getProfileImage = (item) => (item ? item.image : null)
